CREATE TABLE game_genres
(
    game_id  BIGINT  NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT pk_game_genres PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE game_platforms
(
    game_id     BIGINT  NOT NULL,
    platform_id INTEGER NOT NULL,
    CONSTRAINT pk_game_platforms PRIMARY KEY (game_id, platform_id)
);

CREATE TABLE games
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           TEXT                                    NOT NULL,
    description     TEXT,
    cover_image_url VARCHAR(255),
    release_date    date                                    NOT NULL,
    developer       VARCHAR(255),
    publisher       VARCHAR(255),
    rawg_game_slug  VARCHAR(255),
    status          VARCHAR(20)                             NOT NULL,
    age_rating      VARCHAR(20),
    mature          BOOLEAN                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    game_id    BIGINT                                  NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    is_read    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE persistent_logins
(
    series    VARCHAR(64) NOT NULL,
    username  VARCHAR(64) NOT NULL,
    token     VARCHAR(64) NOT NULL,
    last_used TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_persistent_logins PRIMARY KEY (series)
);

CREATE TABLE platforms
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_platforms PRIMARY KEY (id)
);

CREATE TABLE preorder_links
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_name VARCHAR(50)                             NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    game_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_preorder_links PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(50)                             NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    password_hash           VARCHAR(255)                            NOT NULL,
    enable_notifications    BOOLEAN                                 NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    account_non_expired     BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    role_id                 INTEGER                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE wishlist_items
(
    added_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id  BIGINT NOT NULL,
    game_id  BIGINT NOT NULL,
    CONSTRAINT pk_wishlist_items PRIMARY KEY (user_id, game_id)
);

ALTER TABLE preorder_links
    ADD CONSTRAINT uc_517d691efe34bbcecab8f5d5f UNIQUE (game_id, url);

ALTER TABLE games
    ADD CONSTRAINT uc_games_rawggameslug UNIQUE (rawg_game_slug);

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

ALTER TABLE platforms
    ADD CONSTRAINT uc_platforms_name UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_games_release_date ON games (release_date);

CREATE INDEX idx_games_status ON games (status);

CREATE INDEX idx_games_title ON games (title);

CREATE INDEX idx_notifications_created_at ON notifications (created_at);

CREATE INDEX idx_notifications_read ON notifications (is_read);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_notifications_user_id ON notifications (user_id);

ALTER TABLE preorder_links
    ADD CONSTRAINT FK_PREORDER_LINKS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE wishlist_items
    ADD CONSTRAINT FK_WISHLIST_ITEMS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE wishlist_items
    ADD CONSTRAINT FK_WISHLIST_ITEMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE game_genres
    ADD CONSTRAINT fk_gamgen_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_genres
    ADD CONSTRAINT fk_gamgen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);

ALTER TABLE game_platforms
    ADD CONSTRAINT fk_gampla_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_platforms
    ADD CONSTRAINT fk_gampla_on_platform FOREIGN KEY (platform_id) REFERENCES platforms (id);